"""empty message

Revision ID: 0b4c7e8f8e80
Revises: 199c46ac5e3a
Create Date: 2026-07-04 15:39:41.471048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4c7e8f8e80'
down_revision = '199c46ac5e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('riesgo_final',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_final',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
