"""empty message

Revision ID: 12b08f5fd37d
Revises: 59ac289b2bab
Create Date: 2026-09-10 02:41:16.405086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b08f5fd37d'
down_revision = '59ac289b2bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_reto', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.drop_column('numero_reto')

    # ### end Alembic commands ###
