"""empty message

Revision ID: 150f529b9957
Revises: 92ffac9bd58a
Create Date: 2026-09-28 12:56:34.141448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150f529b9957'
down_revision = '92ffac9bd58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acepto_politicas', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('fecha_aceptacion_politicas', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('version_politicas', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ip_aceptacion_politicas', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ip_aceptacion_politicas')
        batch_op.drop_column('version_politicas')
        batch_op.drop_column('fecha_aceptacion_politicas')
        batch_op.drop_column('acepto_politicas')

    # ### end Alembic commands ###
