"""empty message

Revision ID: 199c46ac5e3a
Revises: c9c37257e160
Create Date: 2026-07-03 23:06:27.546190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199c46ac5e3a'
down_revision = 'c9c37257e160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('riesgo_final',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_final',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
