"""empty message

Revision ID: 1a9e838bffb4
Revises: 0b4c7e8f8e80
Create Date: 2026-07-04 15:41:26.414416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9e838bffb4'
down_revision = '0b4c7e8f8e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('riesgo_final',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('riesgo_final',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('riesgo_previo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
