"""empty message

Revision ID: 1f644bd79bb2
Revises: 8614a2957cf2
Create Date: 2026-07-06 16:02:55.652244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f644bd79bb2'
down_revision = '8614a2957cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditar_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.Column('valor_respondido', sa.Text(), nullable=True),
    sa.Column('puntos_ganados', sa.Float(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_formulario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditar_dos')
    # ### end Alembic commands ###
