"""empty message

Revision ID: 264d3b76881b
Revises: 5c4ae9eac5e7
Create Date: 2026-07-04 17:21:15.174088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '264d3b76881b'
down_revision = '5c4ae9eac5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostener_docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuestas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.alter_column('periodo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('promedio_global',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('promedio_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('promedio_d2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('promedio_d3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('promedio_d4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('nivel_calculado',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('alertas_activas',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('porcentaje_crecimiento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('prioridad_sostener',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fecha_revision_plan',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('sostener_docentes_id_sostener_key'), type_='unique')
        batch_op.drop_column('d4_p21')
        batch_op.drop_column('d3_p18')
        batch_op.drop_column('d4_p20')
        batch_op.drop_column('d2_p10')
        batch_op.drop_column('d1_p5')
        batch_op.drop_column('d3_p14')
        batch_op.drop_column('d1_p2')
        batch_op.drop_column('d1_p4')
        batch_op.drop_column('d4_p19')
        batch_op.drop_column('d2_p9')
        batch_op.drop_column('d2_p7')
        batch_op.drop_column('d4_p23')
        batch_op.drop_column('d3_p17')
        batch_op.drop_column('d1_p6')
        batch_op.drop_column('d3_p15')
        batch_op.drop_column('d3_p16')
        batch_op.drop_column('d1_p1')
        batch_op.drop_column('d1_p3')
        batch_op.drop_column('d2_p11')
        batch_op.drop_column('d3_p13')
        batch_op.drop_column('d4_p24')
        batch_op.drop_column('d2_p8')
        batch_op.drop_column('id_sostener')
        batch_op.drop_column('d4_p22')
        batch_op.drop_column('d2_p12')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostener_docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d2_p12', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p22', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_sostener', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('d2_p8', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p24', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p13', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d2_p11', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p3', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p16', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p15', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p6', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p17', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p23', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d2_p7', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d2_p9', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p19', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p4', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p14', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d1_p5', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d2_p10', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p20', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d3_p18', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('d4_p21', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('sostener_docentes_id_sostener_key'), ['id_sostener'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('fecha_revision_plan',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('prioridad_sostener',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('porcentaje_crecimiento',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alertas_activas',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('nivel_calculado',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('promedio_d4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('promedio_d3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('promedio_d2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('promedio_d1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('promedio_global',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('periodo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('respuestas')

    # ### end Alembic commands ###
