"""empty message

Revision ID: 34cbfdcbb72a
Revises: 931b99ee1dfd
Create Date: 2026-06-30 18:17:16.615914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cbfdcbb72a'
down_revision = '931b99ee1dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contexto_narrativo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mision_texto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objetivos_aprendizaje', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preguntas_orientadoras', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('conceptos_clave', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.drop_column('conceptos_clave')
        batch_op.drop_column('preguntas_orientadoras')
        batch_op.drop_column('objetivos_aprendizaje')
        batch_op.drop_column('mision_texto')
        batch_op.drop_column('contexto_narrativo')

    # ### end Alembic commands ###
