"""empty message

Revision ID: 59ac289b2bab
Revises: 1f644bd79bb2
Create Date: 2026-09-02 02:44:06.142416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ac289b2bab'
down_revision = '1f644bd79bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_credencial', sa.String(length=60), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('programa', sa.String(length=300), nullable=False),
    sa.Column('fases_completadas', sa.JSON(), nullable=True),
    sa.Column('huella_final', sa.Float(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_credencial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credenciales')
    # ### end Alembic commands ###
