"""empty message

Revision ID: 5c4ae9eac5e7
Revises: 1a9e838bffb4
Create Date: 2026-07-04 15:47:41.877125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4ae9eac5e7'
down_revision = '1a9e838bffb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('estandar_seleccionado',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.alter_column('estandar_seleccionado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
