"""empty message

Revision ID: 8614a2957cf2
Revises: 264d3b76881b
Create Date: 2026-07-05 19:34:26.002928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8614a2957cf2'
down_revision = '264d3b76881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constructor_prompt', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reescrituras_aplicadas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('lecciones_vistas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('puntaje_rector', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reduccion_riesgo_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('compromiso_datos', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asegurar_docentes', schema=None) as batch_op:
        batch_op.drop_column('compromiso_datos')
        batch_op.drop_column('reduccion_riesgo_pct')
        batch_op.drop_column('puntaje_rector')
        batch_op.drop_column('lecciones_vistas')
        batch_op.drop_column('reescrituras_aplicadas')
        batch_op.drop_column('constructor_prompt')

    # ### end Alembic commands ###
