"""empty message

Revision ID: 92ffac9bd58a
Revises: 9b74e8207c47
Create Date: 2026-09-11 00:51:02.583360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ffac9bd58a'
down_revision = '9b74e8207c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostener_institucional', schema=None) as batch_op:
        batch_op.alter_column('estado_cumplimiento_asegurar',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostener_institucional', schema=None) as batch_op:
        batch_op.alter_column('estado_cumplimiento_asegurar',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
