"""empty message

Revision ID: 931b99ee1dfd
Revises: 
Create Date: 2026-06-17 01:05:25.396697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931b99ee1dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_inicio_atlas', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_key', sa.String(length=100), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('huella_compass_total', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('teacher_key')
    )
    op.create_table('asegurar_directivo_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gobernanza_1_politica', sa.Integer(), nullable=True),
    sa.Column('gobernanza_2_responsable', sa.Integer(), nullable=True),
    sa.Column('gobernanza_3_evaluacion_htas', sa.Integer(), nullable=True),
    sa.Column('gobernanza_4_protocolo_incidentes', sa.Integer(), nullable=True),
    sa.Column('competencia_1_etica', sa.Integer(), nullable=True),
    sa.Column('competencia_2_unesco_levels', sa.Integer(), nullable=True),
    sa.Column('competencia_3_plan_progresivo', sa.Integer(), nullable=True),
    sa.Column('competencia_4_reflexion_critica', sa.Integer(), nullable=True),
    sa.Column('datos_1_protocolo_estudiantes', sa.Integer(), nullable=True),
    sa.Column('datos_2_anonimizacion', sa.Integer(), nullable=True),
    sa.Column('datos_3_terminos_htas', sa.Integer(), nullable=True),
    sa.Column('datos_4_almacenamiento', sa.Integer(), nullable=True),
    sa.Column('supervision_1_decision_humana', sa.Integer(), nullable=True),
    sa.Column('supervision_2_no_automatizada', sa.Integer(), nullable=True),
    sa.Column('supervision_3_monitoreo_ia', sa.Integer(), nullable=True),
    sa.Column('supervision_4_revision_practicas', sa.Integer(), nullable=True),
    sa.Column('transparencia_1_informa_estud', sa.Integer(), nullable=True),
    sa.Column('transparencia_2_lineamientos_uso', sa.Integer(), nullable=True),
    sa.Column('transparencia_3_alfabetizacion', sa.Integer(), nullable=True),
    sa.Column('transparencia_4_declaracion_pub', sa.Integer(), nullable=True),
    sa.Column('puntaje_total_radar', sa.Integer(), nullable=True),
    sa.Column('clasificacion_final', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('asegurar_directivo_panorama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visto_bloque_1_regulatorio', sa.Boolean(), nullable=False),
    sa.Column('visto_bloque_2_competencias', sa.Boolean(), nullable=False),
    sa.Column('visto_bloque_3_etica', sa.Boolean(), nullable=False),
    sa.Column('visto_bloque_4_cultura', sa.Boolean(), nullable=False),
    sa.Column('feedback_opcional_panorama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('asegurar_directivo_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dimension_prioridad_1', sa.String(length=100), nullable=True),
    sa.Column('dimension_prioridad_2', sa.String(length=100), nullable=True),
    sa.Column('objetivo_estrategico', sa.Text(), nullable=True),
    sa.Column('acciones_seleccionadas', sa.JSON(), nullable=True),
    sa.Column('responsables_asignados', sa.JSON(), nullable=True),
    sa.Column('cronograma_estimado', sa.String(length=200), nullable=True),
    sa.Column('indicadores_exito', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('asegurar_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_original', sa.Text(), nullable=True),
    sa.Column('alertas_detectadas', sa.JSON(), nullable=True),
    sa.Column('bloques_activados', sa.JSON(), nullable=True),
    sa.Column('prompt_mejorado', sa.Text(), nullable=True),
    sa.Column('riesgo_previo', sa.String(length=50), nullable=True),
    sa.Column('riesgo_final', sa.String(length=50), nullable=True),
    sa.Column('reflexion_1_cambios', sa.Text(), nullable=True),
    sa.Column('reflexion_2_riesgos', sa.Text(), nullable=True),
    sa.Column('reflexion_3_supervision', sa.Text(), nullable=True),
    sa.Column('reflexion_4_cognicion', sa.Text(), nullable=True),
    sa.Column('estandar_seleccionado', sa.String(length=100), nullable=True),
    sa.Column('url_doc_exportable', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('configuracion_fases_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_activa', sa.Boolean(), nullable=False),
    sa.Column('descripcion_admin', sa.Text(), nullable=True),
    sa.Column('creado_por_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fase_atlas', sa.String(length=20), nullable=False),
    sa.Column('puntos_maximos', sa.Float(), nullable=False),
    sa.Column('rol_destino', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creado_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_admin_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_form')
    )
    op.create_table('huella_compass_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pts_auditar', sa.Float(), nullable=False),
    sa.Column('pts_transformar', sa.Float(), nullable=False),
    sa.Column('pts_liderar', sa.Float(), nullable=False),
    sa.Column('pts_asegurar', sa.Float(), nullable=False),
    sa.Column('pts_sostener', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('evento_trigger', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_ia', sa.String(length=200), nullable=False),
    sa.Column('uso_principal', sa.String(length=300), nullable=True),
    sa.Column('riesgo_detectado', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_fases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('capa_1_sentido', sa.Text(), nullable=True),
    sa.Column('capa_3_hito_texto', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_micromodulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.String(length=100), nullable=False),
    sa.Column('status_lectura', sa.String(length=20), nullable=False),
    sa.Column('nota_quiz', sa.Float(), nullable=True),
    sa.Column('actividad_texto', sa.Text(), nullable=True),
    sa.Column('foro_aporte', sa.Text(), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts_liderar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prompt_original', sa.Text(), nullable=False),
    sa.Column('categoria_uso', sa.String(length=100), nullable=True),
    sa.Column('puntaje_etica', sa.Float(), nullable=False),
    sa.Column('puntaje_privacidad', sa.Float(), nullable=False),
    sa.Column('puntaje_agencia', sa.Float(), nullable=False),
    sa.Column('puntaje_dependencia', sa.Float(), nullable=False),
    sa.Column('simulador_puntaje', sa.Float(), nullable=False),
    sa.Column('clasificacion_riesgo', sa.String(length=50), nullable=True),
    sa.Column('sugerencia_mejora', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('es_publico', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retos_plantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('nivel_unesco', sa.String(length=20), nullable=True),
    sa.Column('rol_destino', sa.String(length=20), nullable=False),
    sa.Column('peso_huella', sa.Float(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creado_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_admin_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento_directivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion_activada', sa.String(length=100), nullable=True),
    sa.Column('dimension_priorizada', sa.String(length=100), nullable=True),
    sa.Column('docente_mentor_key', sa.String(length=100), nullable=True),
    sa.Column('cumplimiento_validado', sa.Boolean(), nullable=False),
    sa.Column('riesgo_alto_actual', sa.String(length=100), nullable=True),
    sa.Column('fase_asegurar_status', sa.String(length=50), nullable=True),
    sa.Column('entendido_gobernanza', sa.Boolean(), nullable=False),
    sa.Column('fecha_accion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sostener_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sostener', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('d1_p1', sa.Integer(), nullable=True),
    sa.Column('d1_p2', sa.Integer(), nullable=True),
    sa.Column('d1_p3', sa.Integer(), nullable=True),
    sa.Column('d1_p4', sa.Integer(), nullable=True),
    sa.Column('d1_p5', sa.Integer(), nullable=True),
    sa.Column('d1_p6', sa.Integer(), nullable=True),
    sa.Column('d2_p7', sa.Integer(), nullable=True),
    sa.Column('d2_p8', sa.Integer(), nullable=True),
    sa.Column('d2_p9', sa.Integer(), nullable=True),
    sa.Column('d2_p10', sa.Integer(), nullable=True),
    sa.Column('d2_p11', sa.Integer(), nullable=True),
    sa.Column('d2_p12', sa.Integer(), nullable=True),
    sa.Column('d3_p13', sa.Integer(), nullable=True),
    sa.Column('d3_p14', sa.Integer(), nullable=True),
    sa.Column('d3_p15', sa.Integer(), nullable=True),
    sa.Column('d3_p16', sa.Integer(), nullable=True),
    sa.Column('d3_p17', sa.Integer(), nullable=True),
    sa.Column('d3_p18', sa.Integer(), nullable=True),
    sa.Column('d4_p19', sa.Integer(), nullable=True),
    sa.Column('d4_p20', sa.Integer(), nullable=True),
    sa.Column('d4_p21', sa.Integer(), nullable=True),
    sa.Column('d4_p22', sa.Integer(), nullable=True),
    sa.Column('d4_p23', sa.Integer(), nullable=True),
    sa.Column('d4_p24', sa.Integer(), nullable=True),
    sa.Column('promedio_global', sa.Float(), nullable=True),
    sa.Column('nivel_calculado', sa.String(length=10), nullable=True),
    sa.Column('promedio_d1', sa.Float(), nullable=True),
    sa.Column('promedio_d2', sa.Float(), nullable=True),
    sa.Column('promedio_d3', sa.Float(), nullable=True),
    sa.Column('promedio_d4', sa.Float(), nullable=True),
    sa.Column('alertas_activas', sa.Integer(), nullable=True),
    sa.Column('porcentaje_crecimiento', sa.Float(), nullable=True),
    sa.Column('reflexion_antes', sa.Text(), nullable=True),
    sa.Column('reflexion_despues', sa.Text(), nullable=True),
    sa.Column('aprendizaje_clave', sa.Text(), nullable=True),
    sa.Column('prioridad_sostener', sa.String(length=100), nullable=True),
    sa.Column('compromiso_accion', sa.Text(), nullable=True),
    sa.Column('evidencia_mejora', sa.Text(), nullable=True),
    sa.Column('fecha_revision_plan', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sostener')
    )
    op.create_table('sostener_institucional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sostener_inst', sa.String(length=100), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reflexion_punto_partida', sa.Text(), nullable=True),
    sa.Column('estado_cumplimiento_asegurar', sa.String(length=50), nullable=True),
    sa.Column('analisis_implementacion', sa.Text(), nullable=True),
    sa.Column('nivel_institucional_actual', sa.String(length=50), nullable=True),
    sa.Column('docentes_n1', sa.Integer(), nullable=True),
    sa.Column('porcentaje_reduccion_alertas', sa.Float(), nullable=True),
    sa.Column('ruta_elegida', sa.String(length=200), nullable=True),
    sa.Column('prioridad_estrategica_anual', sa.Text(), nullable=True),
    sa.Column('accion_gobernanza', sa.Text(), nullable=True),
    sa.Column('indicador_medible', sa.Text(), nullable=True),
    sa.Column('fecha_revision_institucional', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estrategia_comunicacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sostener_inst')
    )
    op.create_table('asignaciones_formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones_retos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('reto_plantilla_id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['reto_plantilla_id'], ['retos_plantilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.Text(), nullable=False),
    sa.Column('tipo_respuesta', sa.String(length=30), nullable=False),
    sa.Column('opciones_seleccion', sa.JSON(), nullable=True),
    sa.Column('puntaje_asociado', sa.Float(), nullable=False),
    sa.Column('orden_pregunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retos_liderar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('reto_plantilla_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_json', sa.JSON(), nullable=True),
    sa.Column('reflexion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reto_plantilla_id'], ['retos_plantilla.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retos_transformar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('reto_plantilla_id', sa.Integer(), nullable=True),
    sa.Column('numero_reto', sa.Integer(), nullable=False),
    sa.Column('nombre_reto', sa.String(length=300), nullable=True),
    sa.Column('nivel_unesco', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('datos_json', sa.JSON(), nullable=True),
    sa.Column('reflexion_1', sa.Text(), nullable=True),
    sa.Column('reflexion_2', sa.Text(), nullable=True),
    sa.Column('decision_final', sa.Text(), nullable=True),
    sa.Column('autoevaluacion_status', sa.String(length=50), nullable=True),
    sa.Column('estado_revision_directivo', sa.String(length=50), nullable=True),
    sa.Column('feedback_directivo', sa.Text(), nullable=True),
    sa.Column('status_reto', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['reto_plantilla_id'], ['retos_plantilla.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.Column('valor_respondido', sa.Text(), nullable=True),
    sa.Column('puntos_ganados', sa.Float(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_formulario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_formulario')
    op.drop_table('retos_transformar')
    op.drop_table('retos_liderar')
    op.drop_table('preguntas_formulario')
    op.drop_table('asignaciones_retos')
    op.drop_table('asignaciones_formularios')
    op.drop_table('sostener_institucional')
    op.drop_table('sostener_docentes')
    op.drop_table('seguimiento_directivo')
    op.drop_table('retos_plantilla')
    op.drop_table('prompts_liderar')
    op.drop_table('progreso_micromodulos')
    op.drop_table('progreso_fases')
    op.drop_table('inventario_ia')
    op.drop_table('huella_compass_history')
    op.drop_table('formularios')
    op.drop_table('configuracion_fases_empresa')
    op.drop_table('asegurar_docentes')
    op.drop_table('asegurar_directivo_plan')
    op.drop_table('asegurar_directivo_panorama')
    op.drop_table('asegurar_directivo_diagnostico')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
