"""empty message

Revision ID: 9b74e8207c47
Revises: 12b08f5fd37d
Create Date: 2026-09-10 18:36:31.501889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b74e8207c47'
down_revision = '12b08f5fd37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dilemas_liderar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('casos_asignados', sa.JSON(), nullable=True),
    sa.Column('selecciones', sa.JSON(), nullable=True),
    sa.Column('conteo_principios', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dilemas_liderar')
    # ### end Alembic commands ###
