"""empty message

Revision ID: bc1b9a274bee
Revises: 34cbfdcbb72a
Create Date: 2026-06-30 19:28:44.870968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1b9a274bee'
down_revision = '34cbfdcbb72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autoevaluacion_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.drop_column('autoevaluacion_items')

    # ### end Alembic commands ###
