"""empty message

Revision ID: c9c37257e160
Revises: e0f8da3ce304
Create Date: 2026-07-03 17:14:35.805155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c37257e160'
down_revision = 'e0f8da3ce304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts_liderar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle_respuestas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dimension_mas_baja', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts_liderar', schema=None) as batch_op:
        batch_op.drop_column('dimension_mas_baja')
        batch_op.drop_column('detalle_respuestas')

    # ### end Alembic commands ###
