"""empty message

Revision ID: e0f8da3ce304
Revises: bc1b9a274bee
Create Date: 2026-07-01 01:11:18.012995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f8da3ce304'
down_revision = 'bc1b9a274bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lectura_previa', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retos_plantilla', schema=None) as batch_op:
        batch_op.drop_column('lectura_previa')

    # ### end Alembic commands ###
